### ISSUE TITLE
CodeStream  is no longer what it was

### ISSUE THREAD

**Issue by Kampouse** [dalys/awesome-linear#18]
i seen  the list and i used codestream  but its no longer a collaborative  plugin for   instance : vscode

**Comment by dalys** [comment]
I don't know what CodeStream is, but maybe you could do a PR with suggested edit? Thanks!

**Comment by Kampouse** [comment]
Code stream allowed you to open pr  checkout branches make issue from within the application 
Its has been replace with a extension for observability for new relic 
tldr: remove it from the list

**Comment by dalys** [comment]
Ah ok, got it!
